version: "3.9"

services:
  redis:
    image: redis:4.0.5-alpine
    container_name: redis-server
    command: ["redis-server", "--appendonly", "yes"]
    ports:
        - 6379:6379
    restart: always
